Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -19,12 +19,18 @@ jobs:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
+      - name: Verify Dockerfile exists
+        run: |
+          if [ ! -f Dockerfile ]; then
+            echo "Dockerfile not found!"
+            exit 1
+          fi
+
       - name: Build and push Docker image
-        uses: docker/build-push-action@v2
-        with:
-          context: .
-          push: true
-          tags: kunj22/python-app:latest
+        run: |
+          docker build. --file Dockerfile --tag my-image-name:$(date +%s)
+          docker tag my-image-name:$(date +%s) kunj22/python-app:latest
+          docker push kunj22/python-app:latest
 
       - name: SSH into the EC2 instance and pull the updated image
         uses: appleboy/ssh-action@master
@@ -36,5 +42,4 @@ jobs:
             docker pull kunj22/python-app:latest
             docker stop python-app-container || true
             docker rm python-app-container || true
-            docker run -d -p 80:80 --name python-app-container kunj22/python-app: latest
-
+            docker run -d -p 80:80 --name python-app-container kunj22/python-app:latest
